package modem

// Warnings shared by several catalog entries.
const (
	warnResetsStartup = "Resets settings the gateway configures at startup (echo off, SMS text mode, verbose errors). " +
		"Sending and receiving may fail until the gateway is restarted."
	warnMarksRead = "Reading messages marks unread ones as read on the SIM. The gateway only imports unread messages, " +
		"so anything read here never reaches the inbox."
	warnNeedsPrompt = "This command waits for message text after a \">\" prompt, which this console cannot provide. " +
		"The modem stays blocked until it times out. Use the Send SMS page instead."
)

// ATCatalog documents the AT commands a GSM modem commonly supports: the
// ITU-T V.250 basics, 3GPP TS 27.007 for the device, network and SIM, and
// 3GPP TS 27.005 for SMS. It drives validation and confirmation of raw
// commands and the WebUI's autocomplete. Risk ratings are about this gateway:
// a command is dangerous when it can stop the gateway sending or receiving,
// lose messages, or cost money.
var ATCatalog = []ATCommandInfo{
	// --- General ---
	{
		Name:        "",
		Title:       "Attention",
		Category:    "General",
		Description: "Checks that the modem is responding. It answers OK and does nothing else.",
		Forms:       []ATForm{{Kind: FormExecute, Syntax: "AT", Description: "Ping the modem."}},
		Response:    "OK",
		Example:     "AT",
		Risk:        RiskSafe,
		Reference:   "ITU-T V.250",
	},
	{
		Name:        "I",
		Title:       "Product identification",
		Category:    "General",
		Description: "Returns manufacturer-specific identification such as the model and firmware.",
		Forms:       []ATForm{{Kind: FormExecute, Syntax: "ATI", Description: "Show identification."}},
		Example:     "ATI",
		Risk:        RiskSafe,
		Reference:   "ITU-T V.250 §6.1.3",
	},
	{
		Name:        "E",
		Title:       "Command echo",
		Category:    "General",
		Description: "Controls whether the modem echoes commands back.",
		Forms: []ATForm{
			{Kind: FormSet, Syntax: "ATE<n>", Description: "Turn echo on or off."},
		},
		Params: []ATParam{{Name: "n", Description: "Echo mode.", Values: []ATParamValue{
			{Value: "0", Description: "Echo off (what the gateway uses)"},
			{Value: "1", Description: "Echo on"},
		}}},
		Example:   "ATE0",
		Risk:      RiskConfig,
		Warning:   "The gateway expects echo off. With ATE1 responses include the command itself; send ATE0 to restore.",
		Reference: "ITU-T V.250 §6.2.4",
	},
	{
		Name:        "V",
		Title:       "Result code format",
		Category:    "General",
		Description: "Chooses verbose (OK / ERROR) or numeric (0 / 4) result codes.",
		Forms:       []ATForm{{Kind: FormSet, Syntax: "ATV<n>", Description: "Set the result code format."}},
		Params: []ATParam{{Name: "n", Description: "Format.", Values: []ATParamValue{
			{Value: "0", Description: "Numeric codes"},
			{Value: "1", Description: "Verbose codes (required by the gateway)"},
		}}},
		Example:   "ATV1",
		Risk:      RiskDangerous,
		Warning:   "The gateway recognises replies by the words OK and ERROR. Numeric codes (ATV0) make every command appear to hang.",
		Reference: "ITU-T V.250 §6.2.6",
	},
	{
		Name:        "Q",
		Title:       "Quiet result codes",
		Category:    "General",
		Description: "Suppresses result codes entirely when set to 1.",
		Forms:       []ATForm{{Kind: FormSet, Syntax: "ATQ<n>", Description: "Enable or suppress result codes."}},
		Params: []ATParam{{Name: "n", Description: "Mode.", Values: []ATParamValue{
			{Value: "0", Description: "Send result codes (required by the gateway)"},
			{Value: "1", Description: "Suppress result codes"},
		}}},
		Example:   "ATQ0",
		Risk:      RiskDangerous,
		Warning:   "Without result codes (ATQ1) the gateway cannot tell when a command finishes, so every command times out.",
		Reference: "ITU-T V.250 §6.2.5",
	},
	{
		Name:        "Z",
		Title:       "Reset to stored profile",
		Category:    "General",
		Description: "Restores the settings saved in the modem's user profile.",
		Forms:       []ATForm{{Kind: FormExecute, Syntax: "ATZ", Description: "Reset settings."}},
		Example:     "ATZ",
		Risk:        RiskDangerous,
		Warning:     warnResetsStartup,
		Reference:   "ITU-T V.250 §6.1.1",
	},
	{
		Name:        "&F",
		Title:       "Factory defaults",
		Category:    "General",
		Description: "Restores the manufacturer's default configuration.",
		Forms:       []ATForm{{Kind: FormExecute, Syntax: "AT&F", Description: "Load factory settings."}},
		Example:     "AT&F",
		Risk:        RiskDangerous,
		Warning:     warnResetsStartup,
		Reference:   "ITU-T V.250 §6.1.2",
	},
	{
		Name:        "&W",
		Title:       "Save profile",
		Category:    "General",
		Description: "Stores the current settings as the user profile that ATZ and power-up restore.",
		Forms:       []ATForm{{Kind: FormExecute, Syntax: "AT&W", Description: "Save current settings."}},
		Example:     "AT&W",
		Risk:        RiskConfig,
	},
	{
		Name:        "+CMEE",
		Title:       "Error reporting",
		Category:    "General",
		Description: "Controls whether errors are reported as a plain ERROR or with a +CME ERROR code or text.",
		Forms: []ATForm{
			{Kind: FormRead, Syntax: "AT+CMEE?", Description: "Show the current mode."},
			{Kind: FormSet, Syntax: "AT+CMEE=<n>", Description: "Set the mode."},
		},
		Params: []ATParam{{Name: "n", Description: "Reporting mode.", Values: []ATParamValue{
			{Value: "0", Description: "Plain ERROR"},
			{Value: "1", Description: "Numeric +CME ERROR codes (gateway default)"},
			{Value: "2", Description: "Verbose +CME ERROR text"},
		}}},
		Response:  "+CMEE: <n>",
		Example:   "AT+CMEE=2",
		Risk:      RiskConfig,
		Reference: "3GPP TS 27.007 §9.1",
	},
	{
		Name:        "+CLAC",
		Title:       "List available commands",
		Category:    "General",
		Description: "Lists every AT command the modem supports, one per line. The console uses it to mark which suggestions this modem accepts.",
		Forms:       []ATForm{{Kind: FormExecute, Syntax: "AT+CLAC", Description: "List supported commands."}},
		Response:    "<command>\n<command>\n...",
		Example:     "AT+CLAC",
		Risk:        RiskSafe,
		Reference:   "3GPP TS 27.007 §8.37",
	},

	// --- Device ---
	{
		Name:        "+CGMI",
		Title:       "Manufacturer",
		Category:    "Device",
		Description: "Returns the manufacturer name.",
		Forms:       []ATForm{{Kind: FormExecute, Syntax: "AT+CGMI", Description: "Show the manufacturer."}},
		Example:     "AT+CGMI",
		Risk:        RiskSafe,
		Reference:   "3GPP TS 27.007 §5.1",
	},
	{
		Name:        "+CGMM",
		Title:       "Model",
		Category:    "Device",
		Description: "Returns the model identification.",
		Forms:       []ATForm{{Kind: FormExecute, Syntax: "AT+CGMM", Description: "Show the model."}},
		Example:     "AT+CGMM",
		Risk:        RiskSafe,
		Reference:   "3GPP TS 27.007 §5.2",
	},
	{
		Name:        "+CGMR",
		Title:       "Firmware revision",
		Category:    "Device",
		Description: "Returns the firmware revision.",
		Forms:       []ATForm{{Kind: FormExecute, Syntax: "AT+CGMR", Description: "Show the firmware revision."}},
		Example:     "AT+CGMR",
		Risk:        RiskSafe,
		Reference:   "3GPP TS 27.007 §5.3",
	},
	{
		Name:        "+CGSN",
		Title:       "IMEI",
		Category:    "Device",
		Description: "Returns the modem's serial number (IMEI).",
		Forms:       []ATForm{{Kind: FormExecute, Syntax: "AT+CGSN", Description: "Show the IMEI."}},
		Example:     "AT+CGSN",
		Risk:        RiskSafe,
		Reference:   "3GPP TS 27.007 §5.4",
	},
	{
		Name:        "+CFUN",
		Title:       "Phone functionality",
		Category:    "Device",
		Description: "Reads or sets the functionality level: full, minimum, or radio off. Some modems also accept a reset flag.",
		Forms: []ATForm{
			{Kind: FormRead, Syntax: "AT+CFUN?", Description: "Show the current level."},
			{Kind: FormTest, Syntax: "AT+CFUN=?", Description: "List supported levels."},
			{Kind: FormSet, Syntax: "AT+CFUN=<fun>[,<rst>]", Description: "Change the level."},
		},
		Params: []ATParam{
			{Name: "fun", Description: "Functionality level.", Values: []ATParamValue{
				{Value: "0", Description: "Minimum functionality"},
				{Value: "1", Description: "Full functionality"},
				{Value: "4", Description: "Radio off (flight mode)"},
			}},
			{Name: "rst", Description: "Reset before changing.", Values: []ATParamValue{
				{Value: "0", Description: "Do not reset"},
				{Value: "1", Description: "Reset the modem"},
			}},
		},
		Response:  "+CFUN: <fun>",
		Example:   "AT+CFUN?",
		Risk:      RiskDangerous,
		Warning:   "Levels other than 1 turn the radio off, so no SMS can be sent or received. A reset drops the modem off the serial port.",
		Reference: "3GPP TS 27.007 §8.2",
	},
	{
		Name:        "+CPAS",
		Title:       "Activity status",
		Category:    "Device",
		Description: "Reports whether the modem is ready, ringing or in a call.",
		Forms:       []ATForm{{Kind: FormExecute, Syntax: "AT+CPAS", Description: "Show the activity status."}},
		Params: []ATParam{{Name: "pas", Description: "Status in the response.", Values: []ATParamValue{
			{Value: "0", Description: "Ready"},
			{Value: "2", Description: "Unknown"},
			{Value: "3", Description: "Ringing"},
			{Value: "4", Description: "Call in progress"},
		}}},
		Response:  "+CPAS: <pas>",
		Example:   "AT+CPAS",
		Risk:      RiskSafe,
		Reference: "3GPP TS 27.007 §8.1",
	},
	{
		Name:        "+CCLK",
		Title:       "Clock",
		Category:    "Device",
		Description: "Reads or sets the modem's real-time clock.",
		Forms: []ATForm{
			{Kind: FormRead, Syntax: "AT+CCLK?", Description: "Show the time."},
			{Kind: FormSet, Syntax: `AT+CCLK="<yy/MM/dd,hh:mm:ss±zz>"`, Description: "Set the time (zz is the offset in quarter hours)."},
		},
		Response:  `+CCLK: "<yy/MM/dd,hh:mm:ss±zz>"`,
		Example:   "AT+CCLK?",
		Risk:      RiskConfig,
		Reference: "3GPP TS 27.007 §8.15",
	},

	// --- Network ---
	{
		Name:        "+CSQ",
		Title:       "Signal quality",
		Category:    "Network",
		Description: "Reports received signal strength (rssi) and bit error rate. Signal in dBm is -113 + 2 × rssi.",
		Forms: []ATForm{
			{Kind: FormExecute, Syntax: "AT+CSQ", Description: "Show the signal quality."},
			{Kind: FormTest, Syntax: "AT+CSQ=?", Description: "List supported values."},
		},
		Params: []ATParam{
			{Name: "rssi", Description: "0 is -113 dBm or less, 31 is -51 dBm or more, 99 is unknown."},
			{Name: "ber", Description: "Bit error rate 0-7, 99 is unknown."},
		},
		Response:  "+CSQ: <rssi>,<ber>",
		Example:   "AT+CSQ",
		Risk:      RiskSafe,
		Reference: "3GPP TS 27.007 §8.5",
	},
	{
		Name:        "+CREG",
		Title:       "Network registration",
		Category:    "Network",
		Description: "Shows whether the modem is registered on the network, and controls unsolicited registration reports.",
		Forms: []ATForm{
			{Kind: FormRead, Syntax: "AT+CREG?", Description: "Show the registration status."},
			{Kind: FormSet, Syntax: "AT+CREG=<n>", Description: "Set unsolicited reporting."},
		},
		Params: []ATParam{
			{Name: "n", Description: "Unsolicited reporting.", Values: []ATParamValue{
				{Value: "0", Description: "Disabled"},
				{Value: "1", Description: "Report status changes"},
				{Value: "2", Description: "Report status and cell location"},
			}},
			{Name: "stat", Description: "Status in the response.", Values: []ATParamValue{
				{Value: "0", Description: "Not registered, not searching"},
				{Value: "1", Description: "Registered, home network"},
				{Value: "2", Description: "Not registered, searching"},
				{Value: "3", Description: "Registration denied"},
				{Value: "4", Description: "Unknown"},
				{Value: "5", Description: "Registered, roaming"},
			}},
		},
		Response:  "+CREG: <n>,<stat>",
		Example:   "AT+CREG?",
		Risk:      RiskConfig,
		Warning:   "Unsolicited reports (n=1 or 2) can appear in the middle of other command responses.",
		Reference: "3GPP TS 27.007 §7.2",
	},
	{
		Name:        "+CGREG",
		Title:       "Packet data registration",
		Category:    "Network",
		Description: "Like +CREG but for the packet-switched (GPRS) network.",
		Forms: []ATForm{
			{Kind: FormRead, Syntax: "AT+CGREG?", Description: "Show the registration status."},
			{Kind: FormSet, Syntax: "AT+CGREG=<n>", Description: "Set unsolicited reporting."},
		},
		Params:    []ATParam{{Name: "stat", Description: "Status in the response; same values as +CREG."}},
		Response:  "+CGREG: <n>,<stat>",
		Example:   "AT+CGREG?",
		Risk:      RiskConfig,
		Reference: "3GPP TS 27.007 §10.1.20",
	},
	{
		Name:        "+COPS",
		Title:       "Operator selection",
		Category:    "Network",
		Description: "Shows the current operator, lists available ones, or forces a selection.",
		Forms: []ATForm{
			{Kind: FormRead, Syntax: "AT+COPS?", Description: "Show the current operator."},
			{Kind: FormTest, Syntax: "AT+COPS=?", Description: "Scan for operators (can take over a minute and time out here)."},
			{Kind: FormSet, Syntax: `AT+COPS=<mode>[,<format>[,"<oper>"]]`, Description: "Select an operator."},
		},
		Params: []ATParam{
			{Name: "mode", Description: "Selection mode.", Values: []ATParamValue{
				{Value: "0", Description: "Automatic"},
				{Value: "1", Description: "Manual"},
				{Value: "2", Description: "Deregister from the network"},
				{Value: "4", Description: "Manual, falling back to automatic"},
			}},
			{Name: "format", Description: "Operator name format.", Values: []ATParamValue{
				{Value: "0", Description: "Long alphanumeric"},
				{Value: "1", Description: "Short alphanumeric"},
				{Value: "2", Description: "Numeric (MCC+MNC)"},
			}},
		},
		Response:  `+COPS: <mode>[,<format>,"<oper>"]`,
		Example:   "AT+COPS?",
		Risk:      RiskDangerous,
		Warning:   "Manual selection or deregistration can leave the modem without network service until it is set back to automatic (AT+COPS=0).",
		Reference: "3GPP TS 27.007 §7.3",
	},
	{
		Name:        "+CUSD",
		Title:       "USSD request",
		Category:    "Network",
		Description: "Sends a USSD code such as a balance check. The answer arrives as an unsolicited +CUSD line, often after this console's 5 second timeout.",
		Forms: []ATForm{
			{Kind: FormRead, Syntax: "AT+CUSD?", Description: "Show whether results are reported."},
			{Kind: FormSet, Syntax: `AT+CUSD=1,"<code>",15`, Description: "Send a USSD code."},
		},
		Params:    []ATParam{{Name: "code", Description: "USSD string, for example *100#."}},
		Response:  `+CUSD: <m>,"<text>",<dcs>`,
		Example:   `AT+CUSD=1,"*100#",15`,
		Risk:      RiskConfig,
		Reference: "3GPP TS 27.007 §7.15",
	},

	// --- SIM ---
	{
		Name:        "+CPIN",
		Title:       "SIM PIN",
		Category:    "SIM",
		Description: "Shows whether the SIM is ready or waiting for a PIN or PUK, and enters it.",
		Forms: []ATForm{
			{Kind: FormRead, Syntax: "AT+CPIN?", Description: "Show the SIM state."},
			{Kind: FormSet, Syntax: `AT+CPIN="<pin>"[,"<newpin>"]`, Description: "Enter the PIN (or PUK and a new PIN)."},
		},
		Params: []ATParam{{Name: "code", Description: "State in the response.", Values: []ATParamValue{
			{Value: "READY", Description: "No PIN needed"},
			{Value: "SIM PIN", Description: "Waiting for the PIN"},
			{Value: "SIM PUK", Description: "Waiting for the PUK (PIN blocked)"},
		}}},
		Response:  "+CPIN: <code>",
		Example:   "AT+CPIN?",
		Risk:      RiskDangerous,
		Warning:   "Each wrong PIN uses up an attempt. After three the SIM locks and needs the PUK.",
		Reference: "3GPP TS 27.007 §8.3",
	},
	{
		Name:        "+CLCK",
		Title:       "Facility lock",
		Category:    "SIM",
		Description: "Locks, unlocks or queries facilities such as the SIM PIN requirement or call barring.",
		Forms: []ATForm{
			{Kind: FormTest, Syntax: "AT+CLCK=?", Description: "List supported facilities."},
			{Kind: FormSet, Syntax: `AT+CLCK="<fac>",<mode>[,"<passwd>"]`, Description: "Lock, unlock or query a facility."},
		},
		Params: []ATParam{{Name: "mode", Description: "Operation.", Values: []ATParamValue{
			{Value: "0", Description: "Unlock"},
			{Value: "1", Description: "Lock"},
			{Value: "2", Description: "Query status"},
		}}},
		Example:   `AT+CLCK="SC",2`,
		Risk:      RiskDangerous,
		Warning:   "Enabling the SIM PIN lock (\"SC\") makes the SIM ask for a PIN on every power-up, which stops the gateway until it is entered.",
		Reference: "3GPP TS 27.007 §7.4",
	},
	{
		Name:        "+CPWD",
		Title:       "Change password",
		Category:    "SIM",
		Description: "Changes the password of a facility, such as the SIM PIN.",
		Forms:       []ATForm{{Kind: FormSet, Syntax: `AT+CPWD="<fac>","<oldpwd>","<newpwd>"`, Description: "Change a password."}},
		Example:     `AT+CPWD="SC","1234","4321"`,
		Risk:        RiskDangerous,
		Warning:     "A wrong old password uses up an attempt and can lock the SIM.",
		Reference:   "3GPP TS 27.007 §7.5",
	},
	{
		Name:        "+CIMI",
		Title:       "IMSI",
		Category:    "SIM",
		Description: "Returns the subscriber identity (IMSI) stored on the SIM.",
		Forms:       []ATForm{{Kind: FormExecute, Syntax: "AT+CIMI", Description: "Show the IMSI."}},
		Example:     "AT+CIMI",
		Risk:        RiskSafe,
		Reference:   "3GPP TS 27.007 §5.6",
	},
	{
		Name:        "+CNUM",
		Title:       "Own number",
		Category:    "SIM",
		Description: "Returns the subscriber's own phone number, if the SIM stores it.",
		Forms:       []ATForm{{Kind: FormExecute, Syntax: "AT+CNUM", Description: "Show the phone number."}},
		Response:    `+CNUM: "<alpha>","<number>",<type>`,
		Example:     "AT+CNUM",
		Risk:        RiskSafe,
		Reference:   "3GPP TS 27.007 §7.1",
	},

	// --- SMS ---
	{
		Name:        "+CMGF",
		Title:       "SMS format",
		Category:    "SMS",
		Description: "Selects text or PDU mode for SMS commands. The gateway rests in text mode and switches to PDU mode itself while sending and receiving.",
		Forms: []ATForm{
			{Kind: FormRead, Syntax: "AT+CMGF?", Description: "Show the current mode."},
			{Kind: FormSet, Syntax: "AT+CMGF=<mode>", Description: "Set the mode."},
		},
		Params: []ATParam{{Name: "mode", Description: "SMS format.", Values: []ATParamValue{
			{Value: "0", Description: "PDU mode"},
			{Value: "1", Description: "Text mode"},
		}}},
		Response:  "+CMGF: <mode>",
		Example:   "AT+CMGF?",
		Risk:      RiskConfig,
		Reference: "3GPP TS 27.005 §3.2.3",
	},
	{
		Name:        "+CSCA",
		Title:       "Service centre address",
		Category:    "SMS",
		Description: "Reads or sets the SMS service centre (SMSC) number every outgoing SMS goes through.",
		Forms: []ATForm{
			{Kind: FormRead, Syntax: "AT+CSCA?", Description: "Show the SMSC number."},
			{Kind: FormSet, Syntax: `AT+CSCA="<number>"[,<type>]`, Description: "Set the SMSC number."},
		},
		Response:  `+CSCA: "<number>",<type>`,
		Example:   "AT+CSCA?",
		Risk:      RiskDangerous,
		Warning:   "A wrong service centre number makes every outgoing SMS fail.",
		Reference: "3GPP TS 27.005 §3.3.1",
	},
	{
		Name:        "+CPMS",
		Title:       "Message storage",
		Category:    "SMS",
		Description: "Selects where messages are read, written and received: SIM (\"SM\"), modem (\"ME\") or both (\"MT\"). The response includes used and total slots.",
		Forms: []ATForm{
			{Kind: FormRead, Syntax: "AT+CPMS?", Description: "Show storages and usage."},
			{Kind: FormTest, Syntax: "AT+CPMS=?", Description: "List supported storages."},
			{Kind: FormSet, Syntax: `AT+CPMS="<mem1>"[,"<mem2>"[,"<mem3>"]]`, Description: "Select storages."},
		},
		Params: []ATParam{{Name: "mem1", Description: "Storage for reading, listing and deleting.", Values: []ATParamValue{
			{Value: `"SM"`, Description: "SIM card"},
			{Value: `"ME"`, Description: "Modem memory"},
			{Value: `"MT"`, Description: "SIM and modem memory"},
		}}},
		Response:  `+CPMS: "<mem1>",<used1>,<total1>,...`,
		Example:   "AT+CPMS?",
		Risk:      RiskConfig,
		Warning:   "The gateway reads incoming messages from the selected storage; moving it can hide messages already stored elsewhere.",
		Reference: "3GPP TS 27.005 §3.2.2",
	},
	{
		Name:        "+CNMI",
		Title:       "New message indications",
		Category:    "SMS",
		Description: "Controls how the modem announces new messages. The gateway polls for messages and does not rely on indications.",
		Forms: []ATForm{
			{Kind: FormRead, Syntax: "AT+CNMI?", Description: "Show the current settings."},
			{Kind: FormSet, Syntax: "AT+CNMI=<mode>,<mt>,<bm>,<ds>,<bfr>", Description: "Change the settings."},
		},
		Params: []ATParam{{Name: "mt", Description: "Delivery of new SMS.", Values: []ATParamValue{
			{Value: "0", Description: "No indication"},
			{Value: "1", Description: "Store and send +CMTI with the index"},
			{Value: "2", Description: "Forward directly as +CMT without storing"},
		}}},
		Response:  "+CNMI: <mode>,<mt>,<bm>,<ds>,<bfr>",
		Example:   "AT+CNMI?",
		Risk:      RiskDangerous,
		Warning:   "With mt=2 messages are forwarded without being stored, so the gateway never sees them. Other indications can also interleave with command responses.",
		Reference: "3GPP TS 27.005 §3.4.1",
	},
	{
		Name:        "+CSCS",
		Title:       "Character set",
		Category:    "SMS",
		Description: "Selects the character set used for text-mode strings such as numbers and message text.",
		Forms: []ATForm{
			{Kind: FormRead, Syntax: "AT+CSCS?", Description: "Show the current set."},
			{Kind: FormTest, Syntax: "AT+CSCS=?", Description: "List supported sets."},
			{Kind: FormSet, Syntax: `AT+CSCS="<chset>"`, Description: "Set the character set."},
		},
		Params: []ATParam{{Name: "chset", Description: "Character set.", Values: []ATParamValue{
			{Value: `"GSM"`, Description: "GSM 7-bit default alphabet"},
			{Value: `"IRA"`, Description: "International reference alphabet (ASCII)"},
			{Value: `"UCS2"`, Description: "16-bit Unicode, as hex"},
		}}},
		Example:   "AT+CSCS?",
		Risk:      RiskConfig,
		Reference: "3GPP TS 27.007 §5.5",
	},
	{
		Name:        "+CSMP",
		Title:       "Text mode parameters",
		Category:    "SMS",
		Description: "Sets first octet, validity period, protocol and data coding scheme for messages sent in text mode.",
		Forms: []ATForm{
			{Kind: FormRead, Syntax: "AT+CSMP?", Description: "Show the parameters."},
			{Kind: FormSet, Syntax: "AT+CSMP=<fo>,<vp>,<pid>,<dcs>", Description: "Set the parameters."},
		},
		Example:   "AT+CSMP?",
		Risk:      RiskConfig,
		Reference: "3GPP TS 27.005 §3.3.2",
	},
	{
		Name:        "+CMGL",
		Title:       "List messages",
		Category:    "SMS",
		Description: "Lists messages in the selected storage by status.",
		Forms: []ATForm{
			{Kind: FormTest, Syntax: "AT+CMGL=?", Description: "List supported status values."},
			{Kind: FormSet, Syntax: `AT+CMGL=<stat>`, Description: "List messages with a status."},
		},
		Params: []ATParam{{Name: "stat", Description: "Status (text mode / PDU mode).", Values: []ATParamValue{
			{Value: `"REC UNREAD"`, Description: "Received unread (PDU: 0)"},
			{Value: `"REC READ"`, Description: "Received read (PDU: 1)"},
			{Value: `"STO UNSENT"`, Description: "Stored unsent (PDU: 2)"},
			{Value: `"STO SENT"`, Description: "Stored sent (PDU: 3)"},
			{Value: `"ALL"`, Description: "All messages (PDU: 4)"},
		}}},
		Response:  `+CMGL: <index>,<stat>,"<oa>",...`,
		Example:   `AT+CMGL="REC READ"`,
		Risk:      RiskDangerous,
		Warning:   warnMarksRead,
		Reference: "3GPP TS 27.005 §3.4.2",
	},
	{
		Name:        "+CMGR",
		Title:       "Read message",
		Category:    "SMS",
		Description: "Reads the message stored at an index.",
		Forms:       []ATForm{{Kind: FormSet, Syntax: "AT+CMGR=<index>", Description: "Read one message."}},
		Params:      []ATParam{{Name: "index", Description: "Storage slot, as listed by +CMGL."}},
		Response:    `+CMGR: <stat>,"<oa>",...`,
		Example:     "AT+CMGR=1",
		Risk:        RiskDangerous,
		Warning:     warnMarksRead,
		Reference:   "3GPP TS 27.005 §3.4.3",
	},
	{
		Name:        "+CMGD",
		Title:       "Delete message",
		Category:    "SMS",
		Description: "Deletes the message at an index, or several at once with a delete flag.",
		Forms: []ATForm{
			{Kind: FormTest, Syntax: "AT+CMGD=?", Description: "List used indexes and supported flags."},
			{Kind: FormSet, Syntax: "AT+CMGD=<index>[,<delflag>]", Description: "Delete messages."},
		},
		Params: []ATParam{{Name: "delflag", Description: "What to delete.", Values: []ATParamValue{
			{Value: "0", Description: "Only the message at index"},
			{Value: "1", Description: "All read messages"},
			{Value: "2", Description: "All read and sent messages"},
			{Value: "3", Description: "All read, sent and unsent messages"},
			{Value: "4", Description: "All messages"},
		}}},
		Example:   "AT+CMGD=1",
		Risk:      RiskDangerous,
		Warning:   "Deleted messages are gone for good, including unread ones the gateway has not imported yet.",
		Reference: "3GPP TS 27.005 §3.5.4",
	},
	{
		Name:        "+CMGS",
		Title:       "Send message",
		Category:    "SMS",
		Description: "Sends an SMS. The modem answers with a \">\" prompt and waits for the text or PDU.",
		Forms:       []ATForm{{Kind: FormSet, Syntax: `AT+CMGS="<number>"`, Description: "Start sending a message."}},
		Example:     `AT+CMGS="+15551234567"`,
		Risk:        RiskDangerous,
		Warning:     warnNeedsPrompt,
		Reference:   "3GPP TS 27.005 §3.5.1",
	},
	{
		Name:        "+CMGW",
		Title:       "Write message to storage",
		Category:    "SMS",
		Description: "Stores a message in memory. Like +CMGS it waits for the text after a \">\" prompt.",
		Forms:       []ATForm{{Kind: FormSet, Syntax: `AT+CMGW="<number>"`, Description: "Start writing a message."}},
		Example:     `AT+CMGW="+15551234567"`,
		Risk:        RiskDangerous,
		Warning:     warnNeedsPrompt,
		Reference:   "3GPP TS 27.005 §3.5.3",
	},
	{
		Name:        "+CMSS",
		Title:       "Send stored message",
		Category:    "SMS",
		Description: "Sends a message already held in storage.",
		Forms:       []ATForm{{Kind: FormSet, Syntax: `AT+CMSS=<index>[,"<number>"]`, Description: "Send a stored message."}},
		Example:     "AT+CMSS=3",
		Risk:        RiskDangerous,
		Warning:     "This sends a real SMS, which may be charged, and it is not recorded in the outbox.",
		Reference:   "3GPP TS 27.005 §3.5.2",
	},

	// --- Calls ---
	{
		Name:        "D",
		Title:       "Dial",
		Category:    "Calls",
		Description: "Places a call. End the number with ; for a voice call.",
		Forms:       []ATForm{{Kind: FormSet, Syntax: "ATD<number>;", Description: "Dial a number."}},
		Example:     "ATD+15551234567;",
		Risk:        RiskDangerous,
		Warning:     "This places a real phone call, which may be charged. Hang up with ATH.",
		Reference:   "ITU-T V.250 §6.3.1",
	},
	{
		Name:        "H",
		Title:       "Hang up",
		Category:    "Calls",
		Description: "Ends the current call.",
		Forms:       []ATForm{{Kind: FormExecute, Syntax: "ATH", Description: "Hang up."}},
		Example:     "ATH",
		Risk:        RiskConfig,
		Reference:   "ITU-T V.250 §6.3.6",
	},
	{
		Name:        "A",
		Title:       "Answer",
		Category:    "Calls",
		Description: "Answers an incoming call.",
		Forms:       []ATForm{{Kind: FormExecute, Syntax: "ATA", Description: "Answer the call."}},
		Example:     "ATA",
		Risk:        RiskConfig,
		Reference:   "ITU-T V.250 §6.3.5",
	},
	{
		Name:        "+CLCC",
		Title:       "Current calls",
		Category:    "Calls",
		Description: "Lists calls in progress.",
		Forms:       []ATForm{{Kind: FormExecute, Syntax: "AT+CLCC", Description: "List current calls."}},
		Response:    `+CLCC: <id>,<dir>,<stat>,<mode>,<mpty>,"<number>",<type>`,
		Example:     "AT+CLCC",
		Risk:        RiskSafe,
		Reference:   "3GPP TS 27.007 §7.18",
	},
}
